name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"   # هر 12 ساعت یک بار (بر اساس UTC)
  workflow_dispatch:          # امکان اجرای دستی از تب Actions

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # سکرتِ توکن
          token: ${{ secrets.METRICS_TOKEN }}

          # اکانت هدف
          user: Arashkazemii

          # قالب و سکشن‌های پایه
          template: classic
          base: header, activity, community, repositories, metadata

          # تایم‌زون برای تاریخ‌ها/گزارش‌ها
          config_timezone: Asia/Tehran

          # افزونه‌ها (plugins) که داشبورد را غنی می‌کنند
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 12
          plugin_languages_sections: most-used, recently-used
          plugin_followup: yes
          plugin_streak: yes
          plugin_calendar: yes
          plugin_achievements: yes
